-- 清空现有数据
DELETE FROM txwl_platform.answer;
DELETE FROM txwl_platform.question;

-- 插入题目和答案
SET @paper_id = 1; -- HRP问卷1的ID

-- 先获取当前最大ID
SELECT MAX(id) INTO @max_question_id FROM txwl_platform.question;

-- 创建题目并同时创建对应答案
INSERT INTO txwl_platform.question (question_text, q_type, paper_id) VALUES 
('您喜欢自我挑战', 'SINGLE', @paper_id),
('您的理科优于文科', 'SINGLE', @paper_id),
('您做事非常细心', 'SINGLE', @paper_id),
('您有时会发脾气', 'SINGLE', @paper_id),
('您对自己要求很高', 'SINGLE', @paper_id),
('您喜欢热闹的环境', 'SINGLE', @paper_id),
('您不太关注他人的工作', 'SINGLE', @paper_id),
('您有时会不冷静', 'SINGLE', @paper_id),
('您有时会感到疲惫', 'SINGLE', @paper_id),
('您每天都会锻炼身体', 'SINGLE', @paper_id),
('您是有耐心的人', 'SINGLE', @paper_id),
('工作时您会很严肃', 'SINGLE', @paper_id),
('您说话比较直接', 'SINGLE', @paper_id),
('您喜欢换着装', 'SINGLE', @paper_id),
('您有时会害羞', 'SINGLE', @paper_id),
('您从来没有吵过架', 'SINGLE', @paper_id),
('您每月都按计划消费', 'SINGLE', @paper_id),
('您经常鼓励身边的人', 'SINGLE', @paper_id),
('您平时说话很少', 'SINGLE', @paper_id),
('您做事小心翼翼', 'SINGLE', @paper_id),
('您经常会面带笑容', 'SINGLE', @paper_id),
('您说话很谨慎', 'SINGLE', @paper_id),
('演讲时您会怯场', 'SINGLE', @paper_id),
('做事前您会准备充分', 'SINGLE', @paper_id),
('您很有勇气', 'SINGLE', @paper_id),
('交流时您会观察对方', 'SINGLE', @paper_id),
('以前的目标您都实现了', 'SINGLE', @paper_id),
('您胆大心细', 'SINGLE', @paper_id),
('您精力非常充沛', 'SINGLE', @paper_id),
('您对自己未来感到迷茫', 'SINGLE', @paper_id),
('您非常善于社交', 'SINGLE', @paper_id),
('您的工作表现非常出色', 'SINGLE', @paper_id),
('您是非常温柔的人', 'SINGLE', @paper_id),
('您非常善解人意', 'SINGLE', @paper_id),
('别人非常喜欢您', 'SINGLE', @paper_id),
('最近您很有耐心', 'SINGLE', @paper_id),
('最近您在家里经常鼓励孩子', 'SINGLE', @paper_id),
('最近在家感到筋疲力尽', 'SINGLE', @paper_id),
('最近您的表现很好', 'SINGLE', @paper_id),
('最近您在家里发过脾气', 'SINGLE', @paper_id),
('最近您在家里说话谨慎', 'SINGLE', @paper_id),
('最近您善解人意', 'SINGLE', @paper_id),
('最近您精力充沛', 'SINGLE', @paper_id),
('最近您经常思考未来', 'SINGLE', @paper_id),
('最近您在家里做事小心翼翼', 'SINGLE', @paper_id),
('最近您在家里非常内向', 'SINGLE', @paper_id),
('最近您的气质优雅', 'SINGLE', @paper_id),
('最近您喜欢热闹的环境', 'SINGLE', @paper_id),
('最近家人都非常喜欢您', 'SINGLE', @paper_id),
('最近您在自我突破', 'SINGLE', @paper_id),
('最近您的改变很多', 'SINGLE', @paper_id),
('最近您没有吵过架', 'SINGLE', @paper_id),
('最近您表现很出色', 'SINGLE', @paper_id),
('最近您有点儿疲惫', 'SINGLE', @paper_id),
('最近您对未来感到迷茫', 'SINGLE', @paper_id),
('最近您的能力与日俱增', 'SINGLE', @paper_id),
('最近您家里的事不太顺利', 'SINGLE', @paper_id),
('最近您压力很大', 'SINGLE', @paper_id),
('最近您的表现很稳定', 'SINGLE', @paper_id),
('最近您无所畏惧', 'SINGLE', @paper_id),
('最近您在家很有魅力', 'SINGLE', @paper_id),
('最近您在家有些郁闷', 'SINGLE', @paper_id),
('最近您非常温柔', 'SINGLE', @paper_id),
('最近您在家里很开心', 'SINGLE', @paper_id),
('最近您在家里说话很多', 'SINGLE', @paper_id),
('最近您很有影响力', 'SINGLE', @paper_id),
('最近您做事非常细心', 'SINGLE', @paper_id),
('最近您有时不冷静', 'SINGLE', @paper_id),
('最近您有时会不好意思', 'SINGLE', @paper_id),
('最近您提高了自我要求', 'SINGLE', @paper_id);

-- 再次查询当前最大ID以确定起始ID
SELECT MAX(id) INTO @current_max_id FROM txwl_platform.question;
SET @total_questions = 70;
SET @first_question_id = @current_max_id - @total_questions + 1;

-- 为每道题创建选项A-E，所有选项都是OPEN类型（因为是单选题）
INSERT INTO txwl_platform.answer (question_id, content, correctness) VALUES 
(@first_question_id + 0, '恰恰相反', 'OPEN'),
(@first_question_id + 0, '不太符合', 'OPEN'),
(@first_question_id + 0, '不确定', 'OPEN'),
(@first_question_id + 0, '比较符合', 'OPEN'),
(@first_question_id + 0, '完全符合', 'OPEN'),

(@first_question_id + 1, '恰恰相反', 'OPEN'),
(@first_question_id + 1, '不太符合', 'OPEN'),
(@first_question_id + 1, '不确定', 'OPEN'),
(@first_question_id + 1, '比较符合', 'OPEN'),
(@first_question_id + 1, '完全符合', 'OPEN'),

(@first_question_id + 2, '恰恰相反', 'OPEN'),
(@first_question_id + 2, '不太符合', 'OPEN'),
(@first_question_id + 2, '不确定', 'OPEN'),
(@first_question_id + 2, '比较符合', 'OPEN'),
(@first_question_id + 2, '完全符合', 'OPEN'),

(@first_question_id + 3, '恰恰相反', 'OPEN'),
(@first_question_id + 3, '不太符合', 'OPEN'),
(@first_question_id + 3, '不确定', 'OPEN'),
(@first_question_id + 3, '比较符合', 'OPEN'),
(@first_question_id + 3, '完全符合', 'OPEN'),

(@first_question_id + 4, '恰恰相反', 'OPEN'),
(@first_question_id + 4, '不太符合', 'OPEN'),
(@first_question_id + 4, '不确定', 'OPEN'),
(@first_question_id + 4, '比较符合', 'OPEN'),
(@first_question_id + 4, '完全符合', 'OPEN'),

(@first_question_id + 5, '恰恰相反', 'OPEN'),
(@first_question_id + 5, '不太符合', 'OPEN'),
(@first_question_id + 5, '不确定', 'OPEN'),
(@first_question_id + 5, '比较符合', 'OPEN'),
(@first_question_id + 5, '完全符合', 'OPEN'),

(@first_question_id + 6, '恰恰相反', 'OPEN'),
(@first_question_id + 6, '不太符合', 'OPEN'),
(@first_question_id + 6, '不确定', 'OPEN'),
(@first_question_id + 6, '比较符合', 'OPEN'),
(@first_question_id + 6, '完全符合', 'OPEN'),

(@first_question_id + 7, '恰恰相反', 'OPEN'),
(@first_question_id + 7, '不太符合', 'OPEN'),
(@first_question_id + 7, '不确定', 'OPEN'),
(@first_question_id + 7, '比较符合', 'OPEN'),
(@first_question_id + 7, '完全符合', 'OPEN'),

(@first_question_id + 8, '恰恰相反', 'OPEN'),
(@first_question_id + 8, '不太符合', 'OPEN'),
(@first_question_id + 8, '不确定', 'OPEN'),
(@first_question_id + 8, '比较符合', 'OPEN'),
(@first_question_id + 8, '完全符合', 'OPEN'),

(@first_question_id + 9, '恰恰相反', 'OPEN'),
(@first_question_id + 9, '不太符合', 'OPEN'),
(@first_question_id + 9, '不确定', 'OPEN'),
(@first_question_id + 9, '比较符合', 'OPEN'),
(@first_question_id + 9, '完全符合', 'OPEN'),

(@first_question_id + 10, '恰恰相反', 'OPEN'),
(@first_question_id + 10, '不太符合', 'OPEN'),
(@first_question_id + 10, '不确定', 'OPEN'),
(@first_question_id + 10, '比较符合', 'OPEN'),
(@first_question_id + 10, '完全符合', 'OPEN'),

(@first_question_id + 11, '恰恰相反', 'OPEN'),
(@first_question_id + 11, '不太符合', 'OPEN'),
(@first_question_id + 11, '不确定', 'OPEN'),
(@first_question_id + 11, '比较符合', 'OPEN'),
(@first_question_id + 11, '完全符合', 'OPEN'),

(@first_question_id + 12, '恰恰相反', 'OPEN'),
(@first_question_id + 12, '不太符合', 'OPEN'),
(@first_question_id + 12, '不确定', 'OPEN'),
(@first_question_id + 12, '比较符合', 'OPEN'),
(@first_question_id + 12, '完全符合', 'OPEN'),

(@first_question_id + 13, '恰恰相反', 'OPEN'),
(@first_question_id + 13, '不太符合', 'OPEN'),
(@first_question_id + 13, '不确定', 'OPEN'),
(@first_question_id + 13, '比较符合', 'OPEN'),
(@first_question_id + 13, '完全符合', 'OPEN'),

(@first_question_id + 14, '恰恰相反', 'OPEN'),
(@first_question_id + 14, '不太符合', 'OPEN'),
(@first_question_id + 14, '不确定', 'OPEN'),
(@first_question_id + 14, '比较符合', 'OPEN'),
(@first_question_id + 14, '完全符合', 'OPEN'),

(@first_question_id + 15, '恰恰相反', 'OPEN'),
(@first_question_id + 15, '不太符合', 'OPEN'),
(@first_question_id + 15, '不确定', 'OPEN'),
(@first_question_id + 15, '比较符合', 'OPEN'),
(@first_question_id + 15, '完全符合', 'OPEN'),

(@first_question_id + 16, '恰恰相反', 'OPEN'),
(@first_question_id + 16, '不太符合', 'OPEN'),
(@first_question_id + 16, '不确定', 'OPEN'),
(@first_question_id + 16, '比较符合', 'OPEN'),
(@first_question_id + 16, '完全符合', 'OPEN'),

(@first_question_id + 17, '恰恰相反', 'OPEN'),
(@first_question_id + 17, '不太符合', 'OPEN'),
(@first_question_id + 17, '不确定', 'OPEN'),
(@first_question_id + 17, '比较符合', 'OPEN'),
(@first_question_id + 17, '完全符合', 'OPEN'),

(@first_question_id + 18, '恰恰相反', 'OPEN'),
(@first_question_id + 18, '不太符合', 'OPEN'),
(@first_question_id + 18, '不确定', 'OPEN'),
(@first_question_id + 18, '比较符合', 'OPEN'),
(@first_question_id + 18, '完全符合', 'OPEN'),

(@first_question_id + 19, '恰恰相反', 'OPEN'),
(@first_question_id + 19, '不太符合', 'OPEN'),
(@first_question_id + 19, '不确定', 'OPEN'),
(@first_question_id + 19, '比较符合', 'OPEN'),
(@first_question_id + 19, '完全符合', 'OPEN'),

(@first_question_id + 20, '恰恰相反', 'OPEN'),
(@first_question_id + 20, '不太符合', 'OPEN'),
(@first_question_id + 20, '不确定', 'OPEN'),
(@first_question_id + 20, '比较符合', 'OPEN'),
(@first_question_id + 20, '完全符合', 'OPEN'),

(@first_question_id + 21, '恰恰相反', 'OPEN'),
(@first_question_id + 21, '不太符合', 'OPEN'),
(@first_question_id + 21, '不确定', 'OPEN'),
(@first_question_id + 21, '比较符合', 'OPEN'),
(@first_question_id + 21, '完全符合', 'OPEN'),

(@first_question_id + 22, '恰恰相反', 'OPEN'),
(@first_question_id + 22, '不太符合', 'OPEN'),
(@first_question_id + 22, '不确定', 'OPEN'),
(@first_question_id + 22, '比较符合', 'OPEN'),
(@first_question_id + 22, '完全符合', 'OPEN'),

(@first_question_id + 23, '恰恰相反', 'OPEN'),
(@first_question_id + 23, '不太符合', 'OPEN'),
(@first_question_id + 23, '不确定', 'OPEN'),
(@first_question_id + 23, '比较符合', 'OPEN'),
(@first_question_id + 23, '完全符合', 'OPEN'),

(@first_question_id + 24, '恰恰相反', 'OPEN'),
(@first_question_id + 24, '不太符合', 'OPEN'),
(@first_question_id + 24, '不确定', 'OPEN'),
(@first_question_id + 24, '比较符合', 'OPEN'),
(@first_question_id + 24, '完全符合', 'OPEN'),

(@first_question_id + 25, '恰恰相反', 'OPEN'),
(@first_question_id + 25, '不太符合', 'OPEN'),
(@first_question_id + 25, '不确定', 'OPEN'),
(@first_question_id + 25, '比较符合', 'OPEN'),
(@first_question_id + 25, '完全符合', 'OPEN'),

(@first_question_id + 26, '恰恰相反', 'OPEN'),
(@first_question_id + 26, '不太符合', 'OPEN'),
(@first_question_id + 26, '不确定', 'OPEN'),
(@first_question_id + 26, '比较符合', 'OPEN'),
(@first_question_id + 26, '完全符合', 'OPEN'),

(@first_question_id + 27, '恰恰相反', 'OPEN'),
(@first_question_id + 27, '不太符合', 'OPEN'),
(@first_question_id + 27, '不确定', 'OPEN'),
(@first_question_id + 27, '比较符合', 'OPEN'),
(@first_question_id + 27, '完全符合', 'OPEN'),

(@first_question_id + 28, '恰恰相反', 'OPEN'),
(@first_question_id + 28, '不太符合', 'OPEN'),
(@first_question_id + 28, '不确定', 'OPEN'),
(@first_question_id + 28, '比较符合', 'OPEN'),
(@first_question_id + 28, '完全符合', 'OPEN'),

(@first_question_id + 29, '恰恰相反', 'OPEN'),
(@first_question_id + 29, '不太符合', 'OPEN'),
(@first_question_id + 29, '不确定', 'OPEN'),
(@first_question_id + 29, '比较符合', 'OPEN'),
(@first_question_id + 29, '完全符合', 'OPEN'),

(@first_question_id + 30, '恰恰相反', 'OPEN'),
(@first_question_id + 30, '不太符合', 'OPEN'),
(@first_question_id + 30, '不确定', 'OPEN'),
(@first_question_id + 30, '比较符合', 'OPEN'),
(@first_question_id + 30, '完全符合', 'OPEN'),

(@first_question_id + 31, '恰恰相反', 'OPEN'),
(@first_question_id + 31, '不太符合', 'OPEN'),
(@first_question_id + 31, '不确定', 'OPEN'),
(@first_question_id + 31, '比较符合', 'OPEN'),
(@first_question_id + 31, '完全符合', 'OPEN'),

(@first_question_id + 32, '恰恰相反', 'OPEN'),
(@first_question_id + 32, '不太符合', 'OPEN'),
(@first_question_id + 32, '不确定', 'OPEN'),
(@first_question_id + 32, '比较符合', 'OPEN'),
(@first_question_id + 32, '完全符合', 'OPEN'),

(@first_question_id + 33, '恰恰相反', 'OPEN'),
(@first_question_id + 33, '不太符合', 'OPEN'),
(@first_question_id + 33, '不确定', 'OPEN'),
(@first_question_id + 33, '比较符合', 'OPEN'),
(@first_question_id + 33, '完全符合', 'OPEN'),

(@first_question_id + 34, '恰恰相反', 'OPEN'),
(@first_question_id + 34, '不太符合', 'OPEN'),
(@first_question_id + 34, '不确定', 'OPEN'),
(@first_question_id + 34, '比较符合', 'OPEN'),
(@first_question_id + 34, '完全符合', 'OPEN'),

(@first_question_id + 35, '恰恰相反', 'OPEN'),
(@first_question_id + 35, '不太符合', 'OPEN'),
(@first_question_id + 35, '不确定', 'OPEN'),
(@first_question_id + 35, '比较符合', 'OPEN'),
(@first_question_id + 35, '完全符合', 'OPEN'),

(@first_question_id + 36, '恰恰相反', 'OPEN'),
(@first_question_id + 36, '不太符合', 'OPEN'),
(@first_question_id + 36, '不确定', 'OPEN'),
(@first_question_id + 36, '比较符合', 'OPEN'),
(@first_question_id + 36, '完全符合', 'OPEN'),

(@first_question_id + 37, '恰恰相反', 'OPEN'),
(@first_question_id + 37, '不太符合', 'OPEN'),
(@first_question_id + 37, '不确定', 'OPEN'),
(@first_question_id + 37, '比较符合', 'OPEN'),
(@first_question_id + 37, '完全符合', 'OPEN'),

(@first_question_id + 38, '恰恰相反', 'OPEN'),
(@first_question_id + 38, '不太符合', 'OPEN'),
(@first_question_id + 38, '不确定', 'OPEN'),
(@first_question_id + 38, '比较符合', 'OPEN'),
(@first_question_id + 38, '完全符合', 'OPEN'),

(@first_question_id + 39, '恰恰相反', 'OPEN'),
(@first_question_id + 39, '不太符合', 'OPEN'),
(@first_question_id + 39, '不确定', 'OPEN'),
(@first_question_id + 39, '比较符合', 'OPEN'),
(@first_question_id + 39, '完全符合', 'OPEN'),

(@first_question_id + 40, '恰恰相反', 'OPEN'),
(@first_question_id + 40, '不太符合', 'OPEN'),
(@first_question_id + 40, '不确定', 'OPEN'),
(@first_question_id + 40, '比较符合', 'OPEN'),
(@first_question_id + 40, '完全符合', 'OPEN'),

(@first_question_id + 41, '恰恰相反', 'OPEN'),
(@first_question_id + 41, '不太符合', 'OPEN'),
(@first_question_id + 41, '不确定', 'OPEN'),
(@first_question_id + 41, '比较符合', 'OPEN'),
(@first_question_id + 41, '完全符合', 'OPEN'),

(@first_question_id + 42, '恰恰相反', 'OPEN'),
(@first_question_id + 42, '不太符合', 'OPEN'),
(@first_question_id + 42, '不确定', 'OPEN'),
(@first_question_id + 42, '比较符合', 'OPEN'),
(@first_question_id + 42, '完全符合', 'OPEN'),

(@first_question_id + 43, '恰恰相反', 'OPEN'),
(@first_question_id + 43, '不太符合', 'OPEN'),
(@first_question_id + 43, '不确定', 'OPEN'),
(@first_question_id + 43, '比较符合', 'OPEN'),
(@first_question_id + 43, '完全符合', 'OPEN'),

(@first_question_id + 44, '恰恰相反', 'OPEN'),
(@first_question_id + 44, '不太符合', 'OPEN'),
(@first_question_id + 44, '不确定', 'OPEN'),
(@first_question_id + 44, '比较符合', 'OPEN'),
(@first_question_id + 44, '完全符合', 'OPEN'),

(@first_question_id + 45, '恰恰相反', 'OPEN'),
(@first_question_id + 45, '不太符合', 'OPEN'),
(@first_question_id + 45, '不确定', 'OPEN'),
(@first_question_id + 45, '比较符合', 'OPEN'),
(@first_question_id + 45, '完全符合', 'OPEN'),

(@first_question_id + 46, '恰恰相反', 'OPEN'),
(@first_question_id + 46, '不太符合', 'OPEN'),
(@first_question_id + 46, '不确定', 'OPEN'),
(@first_question_id + 46, '比较符合', 'OPEN'),
(@first_question_id + 46, '完全符合', 'OPEN'),

(@first_question_id + 47, '恰恰相反', 'OPEN'),
(@first_question_id + 47, '不太符合', 'OPEN'),
(@first_question_id + 47, '不确定', 'OPEN'),
(@first_question_id + 47, '比较符合', 'OPEN'),
(@first_question_id + 47, '完全符合', 'OPEN'),

(@first_question_id + 48, '恰恰相反', 'OPEN'),
(@first_question_id + 48, '不太符合', 'OPEN'),
(@first_question_id + 48, '不确定', 'OPEN'),
(@first_question_id + 48, '比较符合', 'OPEN'),
(@first_question_id + 48, '完全符合', 'OPEN'),

(@first_question_id + 49, '恰恰相反', 'OPEN'),
(@first_question_id + 49, '不太符合', 'OPEN'),
(@first_question_id + 49, '不确定', 'OPEN'),
(@first_question_id + 49, '比较符合', 'OPEN'),
(@first_question_id + 49, '完全符合', 'OPEN'),

(@first_question_id + 50, '恰恰相反', 'OPEN'),
(@first_question_id + 50, '不太符合', 'OPEN'),
(@first_question_id + 50, '不确定', 'OPEN'),
(@first_question_id + 50, '比较符合', 'OPEN'),
(@first_question_id + 50, '完全符合', 'OPEN'),

(@first_question_id + 51, '恰恰相反', 'OPEN'),
(@first_question_id + 51, '不太符合', 'OPEN'),
(@first_question_id + 51, '不确定', 'OPEN'),
(@first_question_id + 51, '比较符合', 'OPEN'),
(@first_question_id + 51, '完全符合', 'OPEN'),

(@first_question_id + 52, '恰恰相反', 'OPEN'),
(@first_question_id + 52, '不太符合', 'OPEN'),
(@first_question_id + 52, '不确定', 'OPEN'),
(@first_question_id + 52, '比较符合', 'OPEN'),
(@first_question_id + 52, '完全符合', 'OPEN'),

(@first_question_id + 53, '恰恰相反', 'OPEN'),
(@first_question_id + 53, '不太符合', 'OPEN'),
(@first_question_id + 53, '不确定', 'OPEN'),
(@first_question_id + 53, '比较符合', 'OPEN'),
(@first_question_id + 53, '完全符合', 'OPEN'),

(@first_question_id + 54, '恰恰相反', 'OPEN'),
(@first_question_id + 54, '不太符合', 'OPEN'),
(@first_question_id + 54, '不确定', 'OPEN'),
(@first_question_id + 54, '比较符合', 'OPEN'),
(@first_question_id + 54, '完全符合', 'OPEN'),

(@first_question_id + 55, '恰恰相反', 'OPEN'),
(@first_question_id + 55, '不太符合', 'OPEN'),
(@first_question_id + 55, '不确定', 'OPEN'),
(@first_question_id + 55, '比较符合', 'OPEN'),
(@first_question_id + 55, '完全符合', 'OPEN'),

(@first_question_id + 56, '恰恰相反', 'OPEN'),
(@first_question_id + 56, '不太符合', 'OPEN'),
(@first_question_id + 56, '不确定', 'OPEN'),
(@first_question_id + 56, '比较符合', 'OPEN'),
(@first_question_id + 56, '完全符合', 'OPEN'),

(@first_question_id + 57, '恰恰相反', 'OPEN'),
(@first_question_id + 57, '不太符合', 'OPEN'),
(@first_question_id + 57, '不确定', 'OPEN'),
(@first_question_id + 57, '比较符合', 'OPEN'),
(@first_question_id + 57, '完全符合', 'OPEN'),

(@first_question_id + 58, '恰恰相反', 'OPEN'),
(@first_question_id + 58, '不太符合', 'OPEN'),
(@first_question_id + 58, '不确定', 'OPEN'),
(@first_question_id + 58, '比较符合', 'OPEN'),
(@first_question_id + 58, '完全符合', 'OPEN'),

(@first_question_id + 59, '恰恰相反', 'OPEN'),
(@first_question_id + 59, '不太符合', 'OPEN'),
(@first_question_id + 59, '不确定', 'OPEN'),
(@first_question_id + 59, '比较符合', 'OPEN'),
(@first_question_id + 59, '完全符合', 'OPEN'),

(@first_question_id + 60, '恰恰相反', 'OPEN'),
(@first_question_id + 60, '不太符合', 'OPEN'),
(@first_question_id + 60, '不确定', 'OPEN'),
(@first_question_id + 60, '比较符合', 'OPEN'),
(@first_question_id + 60, '完全符合', 'OPEN'),

(@first_question_id + 61, '恰恰相反', 'OPEN'),
(@first_question_id + 61, '不太符合', 'OPEN'),
(@first_question_id + 61, '不确定', 'OPEN'),
(@first_question_id + 61, '比较符合', 'OPEN'),
(@first_question_id + 61, '完全符合', 'OPEN'),

(@first_question_id + 62, '恰恰相反', 'OPEN'),
(@first_question_id + 62, '不太符合', 'OPEN'),
(@first_question_id + 62, '不确定', 'OPEN'),
(@first_question_id + 62, '比较符合', 'OPEN'),
(@first_question_id + 62, '完全符合', 'OPEN'),

(@first_question_id + 63, '恰恰相反', 'OPEN'),
(@first_question_id + 63, '不太符合', 'OPEN'),
(@first_question_id + 63, '不确定', 'OPEN'),
(@first_question_id + 63, '比较符合', 'OPEN'),
(@first_question_id + 63, '完全符合', 'OPEN'),

(@first_question_id + 64, '恰恰相反', 'OPEN'),
(@first_question_id + 64, '不太符合', 'OPEN'),
(@first_question_id + 64, '不确定', 'OPEN'),
(@first_question_id + 64, '比较符合', 'OPEN'),
(@first_question_id + 64, '完全符合', 'OPEN'),

(@first_question_id + 65, '恰恰相反', 'OPEN'),
(@first_question_id + 65, '不太符合', 'OPEN'),
(@first_question_id + 65, '不确定', 'OPEN'),
(@first_question_id + 65, '比较符合', 'OPEN'),
(@first_question_id + 65, '完全符合', 'OPEN'),

(@first_question_id + 66, '恰恰相反', 'OPEN'),
(@first_question_id + 66, '不太符合', 'OPEN'),
(@first_question_id + 66, '不确定', 'OPEN'),
(@first_question_id + 66, '比较符合', 'OPEN'),
(@first_question_id + 66, '完全符合', 'OPEN'),

(@first_question_id + 67, '恰恰相反', 'OPEN'),
(@first_question_id + 67, '不太符合', 'OPEN'),
(@first_question_id + 67, '不确定', 'OPEN'),
(@first_question_id + 67, '比较符合', 'OPEN'),
(@first_question_id + 67, '完全符合', 'OPEN'),

(@first_question_id + 68, '恰恰相反', 'OPEN'),
(@first_question_id + 68, '不太符合', 'OPEN'),
(@first_question_id + 68, '不确定', 'OPEN'),
(@first_question_id + 68, '比较符合', 'OPEN'),
(@first_question_id + 68, '完全符合', 'OPEN'),

(@first_question_id + 69, '恰恰相反', 'OPEN'),
(@first_question_id + 69, '不太符合', 'OPEN'),
(@first_question_id + 69, '不确定', 'OPEN'),
(@first_question_id + 69, '比较符合', 'OPEN'),
(@first_question_id + 69, '完全符合', 'OPEN');